---
title: "analyse pp"
author: "Willem Stolte"
date: "2025-08-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, eval=FALSE}
# idea was to load all in database. Still to be done correctly

library(RSQLite)

conn <- dbConnect(RSQLite::SQLite(), "../data/westerschelde.db")
RSQLite::dbListTables(conn)

# check
pp <- dbGetQuery(conn, "SELECT * FROM primaryproduction")

```

```{r}
filelist <- list.files("../data/Deltares/combined_ppp/", full.names = T)
filelist <- filelist[!grepl("old|mean", filelist)]

pp <- lapply(filelist,
             \(x) read_delim(x, delim = ";")
) %>%
  map(
    \(x) x %>% mutate(compartiment = as.character(compartiment))
  ) %>%
  bind_rows() %>%
  mutate(
    compartiment = case_when(
      grepl("7", compartiment) ~ "7", 
      .default = compartiment
    )
  )

```



```{r}
unique(pp$parameter)

```

```{r}

pp %>%
  filter(parameter == "PP_depth_integrated") %>%
  mutate(datetime = as_datetime(datetime)) %>%
  mutate(year = year(datetime), month = month(datetime)) %>%
  group_by(year, month, compartiment, source, method, parameter, unit) %>%
  summarize(monthlyMean = mean(value, na.rm = T)) %T>%
  write_delim("../data/Deltares/combined_ppp/monthly_mean_integrated_ppp") %>%
  mutate(date = ymd(paste(year, month, 15))) %>%
  ggplot(aes(date, monthlyMean)) +
  geom_path(aes(color = source)) +
  facet_wrap("compartiment")
```

